export const homeObjOne = {
    lightBg : true,
    primary: false, 
    imgStart: "", 
    lightTopLine: false, 
    lightText: false, 
    lightTextDesc: false, 
    buttonLabelOne: "Galeria", 
    buttonLabelTwo: "Contato", 
    description: "Ano de Fundação 1918.", 
    headline: "União Sport Club Itabirito", 
    topLine: "Veteranos",
    start: "true", 
    img: require("../../assets/logo.png"), 
    alt: "Image",
}

export const aboutObj = {
    lightBG : true,   
    imgStart: "", 
    lightText: false, 
    ligthTextParag: false, 
    title: "História",    
    paragraph: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    buttonLabel: "Saiba Mais", 
    primary: false,
    start: "true",
    img: require("../../assets/about.jpg"), 
    alt: "About Image",
    showPlus: false,
}

export const galeryObj = {
    lightBG : false,   
    imgStart: "start", 
    lightText: true, 
    ligthTextParag: true, 
    title: "Galeria",    
    paragraph: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    buttonLabel: "imagens", 
    primary: true,
    start: "false",
    img: require("../../assets/about.jpg"), 
    alt: "Galery Image",
    showPlus: true,
}

export const gamesObj = {
    lightBG : true,   
    imgStart: "", 
    lightText: false, 
    ligthTextParag: false, 
    title: "Calendário de Jogos",    
    paragraph: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    buttonLabel: "Saiba Mais", 
    primary: false,
    start: "true",
    img: require("../../assets/about.jpg"), 
    alt: "About Image",
    showPlus: false,
}
