export { default as Navbar } from "./Navbar/Navbar"
export { default as Hero } from "./Hero/Hero"
export { default as Footer } from "./Footer/Footer"
export { default as Subscribe } from "./Subscribe/Subscribe"
export { default as Section } from "./Section/Section"
export { default as Depoiments } from "./Depoiments/Depoiments"
export { default as Stories } from "./Stories/Stories"